lyrics = [
          
          # Good Luck, Babe
    "It's fine, it's cool",
    "You can say that we are nothing, but you know the truth",
    "And guess I'm the fool",
    "With her arms out like an angel through the car sunroof",
    "I don't wanna call it off",
    "But you don't wanna call it love",
    "You only wanna be the one that I call 'baby'",
    "You can kiss a hundred boys in bars",
    "Shoot another shot, try to stop the feeling",
    "You can say it's just the way you are",
    "Make a new excuse, 'nother stupid reason",
    "Good luck, babe (Well, good luck)",
    "Well, good luck, babe (Well, good luck)",
    "You'd have to stop the world just to stop the feeling",
    "Good luck, babe (Well, good luck)",
    "Well, good luck, babe (Well, good luck)",
    "You'd have to stop the world just to stop the feeling",
    "I'm cliché, who cares?",
    "It's a sexually explicit kind of love affair",
    "And I cry, it's not fair",
    "I just need a little lovin', I just need a little air",
    "Think I'm gonna call it off",
    "Even if you call it love",
    "I just wanna love someone who calls me 'baby'",
    "You can kiss a hundred boys in bars",
    "Shoot another shot, try to stop the feeling",
    "You can say it's just the way you are",
    "Make a new excuse, 'nother stupid reason",
    "Good luck, babe (Well, good luck)",
    "Well, good luck, babe (Well, good luck)",
    "You'd have to stop the world just to stop the feeling",
    "Good luck, babe (Well, good luck)",
    "Well, good luck, babe (Well, good luck)",
    "You'd have to stop the world just to stop the feeling",
    "Ah, ah-yeah, oh",
    "When you wake up next to him in the middle of the night",
    "With your head in your hands, you're nothing more than his wife",
    "And when you think about me all of those years ago",
    "You're standing face to face with 'I told you so'",
    "You know I hate to say it, I told you so",
    "You know I hate to say, but I told you so",
    "You can kiss a hundred boys in bars",
    "Shoot another shot, try to stop the feeling (Well, I told you so)",
    "You can say it's just the way you are",
    "Make a new excuse, 'nother stupid reason",
    "Good luck, babe (Well, good luck)",
    "Well, good luck, babe (Well, good luck)",
    "You'd have to stop the world just to stop the feeling",
    "Good luck, babe (Well, good luck)",
    "Well, good luck, babe (Well, good luck)",
    "You'd have to stop the world just to stop the feeling",
    "You'd have to stop the world just to stop the feeling",
    "You'd have to stop the world just to stop the feeling",
          
          # California
          "I stretched myself across four states",
          "New lands, west coast, where my dreams lay",
          "I trade amber clay roads for the",
          "Sea foam and the endless sun rays",
          "Cause I was never told that I wasn't gonna get",
          "The things I want the most",
          "But people always say, 'If it hasn't happened yet",
          "Then maybe you should go'",
          "Come get me out of California",
          "No leaves are brown",
          "I miss the seasons in Missouri",
          "My dying town",
          "Thought I'd be cool in California",
          "I'd make you proud",
          "To think I almost had it going",
          "But I let you down",
          "Too hard to find reasons to stay",
          "Even true love could not persuade",
          "Cause I was never told that I wasn't gonna get",
          "The things I want the most",
          "And people always say, 'If it hasn't happened yet",
          "Then maybe you should go'",
          "Come get me out of California",
          "No leaves are brown",
          "I miss the seasons in Missouri",
          "My dying town",
          "Thought I'd be cool in California",
          "I'd make you proud",
          "To think I almost had it going",
          "But I let you down",
          "Come get me out",
          "Come get me out of California",
          "No leaves are brown",
          "I miss the seasons in Missouri",
          "My dying town",
          "Thought I'd be cool in California",
          "I'd make you proud",
          "To think I almost had it going",
          "But I let you down",
          
          # Femininomenon
    "Same old story, time again",
    "Got so close but then you lost it",
    "Should've listened to your friends",
    "Bout his girlfriend back in Boston",
    "You sent him pictures and playlists and phone sex",
    "He disappeared from the second that you said",
    "Let's get coffee, let's meet up",
    "I'm so sick of online love",
    "And I don't understand",
    "Why can't any man",
    "Hit it like, get it hot",
    "Make a bitch, it's a fem",
    "Hit it like, get it hot",
    "Make a bitch, it's a—",
    "Um, can you play a song with a fucking beat?",
    "(Hit it like) Hit it like rom-pom-pom-pom",
    "(Get it hot) Get it hot like Papa John",
    "(Make a bitch) Make a bitch go on and on",
    "(It's a fem) It's a femininomenon",
    "(Hit it like) Hit it like rom-pom-pom-pom",
    "(Get it hot) Get it hot like Papa John",
    "(Make a bitch) Make a bitch go on and on",
    "(It's a fem) It's a femininomenon",
    "So let's say it's working out",
    "You pretend to love his mother",
    "Lying to your friends about",
    "How he's such a goddamn good lover",
    "Stuck in the suburbs, you're folding his laundry",
    "Got what you wanted, so stop feeling sorry",
    "Crying at the nail salon",
    "I'm so sick of online love",
    "And I don't understand",
    "Why can't any man",
    "Hit it like, get it hot",
    "Make a bitch, it's a fem",
    "Hit it like, get it hot",
    "Make a bitch, it's a—",
    "Dude, can you play a song with a fucking beat?",
    "(Hit it like) Hit it like rom-pom-pom-pom",
    "(Get it hot) Get it hot like Papa John",
    "(Make a bitch) Make a bitch go on and on",
    "(It's a fem) It's a femininomenon",
    "(Hit it like) Hit it like rom-pom-pom-pom",
    "(Get it hot) Get it hot like Papa John",
    "(Make a bitch) Make a bitch go on and on",
    "(It's a fem) It's a femininomenon",
    "Ladies, you know what I mean",
    "And you know what you need",
    "And so does he",
    "But does it happen? (No)",
    "But does it happen? (No)",
    "Well, what we really need is a femininomenon",
    "(A what?) A femininomenon",
    "(Hit it like) Hit it like rom-pom-pom-pom",
    "(Get it hot) Get it hot like Papa John",
    "(Make a bitch) Make a bitch go on and on",
    "(It's a fem) It's a femininomenon",
    "(Hit it like) Hit it like rom-pom-pom-pom",
    "(Get it hot) Get it hot like Papa John",
    "(Make a bitch) Make a bitch go on and on",
    "Did you hear me? Play the fucking beat",
    "Hit it like rom-pom-pom-pom",
    "(Get it hot) Get it hot like Papa John",
    "(Make a bitch) Make a bitch go on and on",
    "(It's a fem) It's a femininomenon",
    "(Hit it like) Hit it like rom-pom-pom-pom",
    "(Get it hot) Get it hot like Papa John",
    "(Make a bitch) Make a bitch go on and on",
    "(It's a fem) It's a femininomenon",
    "Hit it like, get it hot",
    "Make a bitch, it's a fem (It's a femininomenon)",
    "Hit it like, get it hot",
    "Make a bitch, it's a fem, fem, fem, fem"
]
